spring.application.name=myfirstspring
spring.data.mongodb.uri=mongodb+srv://pavanig03:123@java.rhdavki.mongodb.net/?retryWrites=true&w=majority&appName=JAVA
spring.data.mongodb.database=springbootdatabase
server.port=8082
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.servlet.path=/